data:
    dataset_type: "cached_threedfront"
    # encoding_type: "cached_diffusion_cosin_angle_objfeatsnorm_lat32_wocm" #"****_no_prm"
    encoding_type: "cached_diffusion_cosin_angle_objfeatsnorm_lat32_wocm_prmAll" #"****_no_prm"

    dataset_directory: "/building_block/3d_front_processed/bedrooms_objfeats_32_64"
    # dataset_directory: "/dev/shm/bedrooms_objfeats_32_64"

    annotation_file: "/building_block/config/bedroom_threed_front_splits.csv"
    path_to_invalid_scene_ids: "/building_block/config/invalid_threed_front_rooms.txt"
    path_to_invalid_bbox_jids: "/building_block/config/black_list.txt"
    augmentations: ["fixed_rotations"]
    # augmentations: None #["fixed_rotations"]
    filter_fn: "threed_front_bedroom" #"no_filtering"
    train_stats: "dataset_stats.txt"
    room_layout_size: "64,64"
    pad_zero: false #true #false


network:
    type: "diffusion_scene_layout_ddpm"
    # denoising network
    # net_type: "unet1d"
    net_type: "dit_adaln"
    # concate squarewish layer
    point_dim: 62 #29
    latent_dim: 0
    room_mask_condition: false # not use room_mask 
    sample_num_points: 12 # max_length 

    objectness_dim: 0
    class_dim: 22
    angle_dim: 2
    objfeat_dim: 32 #64

    # # class condition
    # learnable_embedding: true
    # instance_condition: true
    # instance_emb_dim: 128

    # class condition
    learnable_embedding: false #true
    instance_condition:  false #true
    instance_emb_dim:    0 #128

    # diffusion config
    diffusion_kwargs:
        schedule_type: 'linear'
        beta_start: 0.0001
        beta_end: 0.02
        time_num: 1000 
        loss_type: 'mse'
        model_mean_type: 'v' #'x0' #'eps'
        model_var_type: 'fixedsmall'
        loss_separate: true
        # calculate iou loss
        loss_iou: true
        # train_stats_file: "../3d_front_processed/bedrooms_objfeats/dataset_stats.txt"
        train_stats_file: "/building_block/3d_front_processed/bedrooms_objfeats_32_64/dataset_stats.txt"

    net_kwargs:
        dim: 512 #encoder/decoder dim
        width: 512 #transformer width
        n_ctx: 12 #64 #length
        time_token_cond: false #t is token or add to hidden_state
        channels: 62 #22 #30 #62 
        objectness_dim: 0
        class_dim: 22
        angle_dim: 2
        objfeat_dim: 32
        context_dim: 0
        instanclass_dim: 0 
        layers: 12 #12 #6 
        seperate_all: true  
        with_window: false #true #false #true
        window_size: 16
        pos_embeding_way: "no_pos_embed" #"learned"
        size_half: true 

feature_extractor:
    name: "resnet18"
    feature_size: 64
    freeze_bn: true
    input_channels: 1

training:
    splits: ["train", "val"]
    epochs: 60001
    steps_per_epoch: 500
    batch_size: 128
    save_frequency: 2000
    max_grad_norm: 10
    # optimizer
    optimizer: Adam
    weight_decay: 0.0
    # schedule
    schedule: 'step'
    lr: 0.0002
    lr_step: 10000
    lr_decay: 0.5

validation:
    splits: ["test"]
    frequency: 1000
    batch_size: 128
    gen_traj: false
    num_step: 100
    gen_gt: false
    gen_prob_map: false

logger:
    type: "wandb"
    project: "BuildingBlock_indoor"
 